# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:12.16

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run linter!
      - run:
          name: Linter
          command: yarn lint

      # run tests!
      - run:
          name: Tests
          command: yarn test

      - persist_to_workspace:
          root: ~/app
          paths: .

  publish:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Publish package
          command: yarn semantic-release

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
